"""Automatic captions: Whisper timestamps -> styled ASS subtitle track."""
from __future__ import annotations

import math
import textwrap
from pathlib import Path

STYLES = {
    "default": {
        "fontname": "Arial", "fontsize": 18, "primary": "&H00FFFFFF",
        "outline": "&H00000000", "bold": 1, "marginv": 40, "max_chars": 42,
    },
    "karaoke": {
        "fontname": "Arial", "fontsize": 22, "primary": "&H0000FFFF",
        "outline": "&H00000000", "bold": 1, "marginv": 60, "max_chars": 36,
    },
    "clean": {
        "fontname": "Helvetica", "fontsize": 16, "primary": "&H00F8F8F8",
        "outline": "&H50000000", "bold": 0, "marginv": 30, "max_chars": 44,
    },
    "bold": {
        "fontname": "Arial Black", "fontsize": 24, "primary": "&H00FFFFFF",
        "outline": "&H00000000", "bold": 1, "marginv": 50, "max_chars": 32,
    },
    "bengali": {
        "fontname": "Noto Sans Bengali", "fontsize": 26, "primary": "&H00FFFFFF",
        "outline": "&H00000000", "bold": 1, "marginv": 70, "max_chars": 28,
    },
    "hindi": {
        "fontname": "Noto Sans Devanagari", "fontsize": 26, "primary": "&H00FFFFFF",
        "outline": "&H00000000", "bold": 1, "marginv": 70, "max_chars": 28,
    },
}

CAPTION_STYLES = tuple(STYLES.keys())


def _ts(t: float) -> str:
    value = max(0, round(t * 100))
    hours, value = divmod(value, 360000)
    minutes, value = divmod(value, 6000)
    seconds, fraction = divmod(value, 100)
    return f"{hours}:{minutes:02d}:{seconds:02d}.{fraction:02d}"


def _subtitle_ts(t: float, separator: str = ",") -> str:
    value = max(0, round(t * 1000))
    hours, value = divmod(value, 3600000)
    minutes, value = divmod(value, 60000)
    seconds, fraction = divmod(value, 1000)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}{separator}{fraction:03d}"


def valid_segments(segments: list[dict]) -> list[dict]:
    result = []
    for segment in segments:
        try:
            start, end = float(segment["start"]), float(segment["end"])
            text = " ".join(str(segment.get("text", "")).split())
            if not math.isfinite(start) or not math.isfinite(end) or end <= max(0, start) or not text:
                continue
            result.append({"start": max(0, start), "end": end, "text": text})
        except (KeyError, TypeError, ValueError):
            continue
    return sorted(result, key=lambda segment: segment["start"])


def trim_segments(segments: list[dict], start: float, end: float) -> list[dict]:
    return [{"start": max(start, segment["start"]) - start,
             "end": min(end, segment["end"]) - start, "text": segment["text"]}
            for segment in valid_segments(segments) if segment["end"] > start and segment["start"] < end]


def segments_to_srt(segments: list[dict]) -> str:
    return "\n\n".join(
        f"{index}\n{_subtitle_ts(segment['start'])} --> {_subtitle_ts(segment['end'])}\n{segment['text']}"
        for index, segment in enumerate(valid_segments(segments), 1)
    ) + "\n"


def segments_to_vtt(segments: list[dict]) -> str:
    return "WEBVTT\n\n" + "\n\n".join(
        f"{_subtitle_ts(segment['start'], '.')} --> {_subtitle_ts(segment['end'], '.')}\n{segment['text']}"
        for segment in valid_segments(segments)
    ) + "\n"


def _ass_text(text: str) -> str:
    return text.replace("\\", "/").replace("{", "(").replace("}", ")")


def segments_to_ass(
    segments: list[dict],
    style: str = "default",
    play_res_x: int = 1080,
    play_res_y: int = 1920,
    max_chars: int | None = None,
    hook_text: str = "",
    hook_seconds: float = 2.0,
) -> str:
    st = STYLES.get(style, STYLES["default"])
    width = max_chars if max_chars is not None else int(st.get("max_chars", 42))
    font_size = round(int(st["fontsize"]) * play_res_y / 640)
    margin = round(int(st["marginv"]) * play_res_y / 640)
    hook_size = round(42 * play_res_y / 1280)
    hook_font = "Arial Black" if style not in ("bengali", "hindi") else st["fontname"]
    lines = [
        "[Script Info]",
        "; generated by ClipForge worker",
        f"PlayResX: {play_res_x}",
        f"PlayResY: {play_res_y}",
        "ScaledBorderAndShadow: yes",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
        "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
        "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        (
            f"Style: Cap,{st['fontname']},{font_size},{st['primary']},&H000000FF,"
            f"{st['outline']},&H80000000,{st['bold']},0,0,0,100,100,0,0,1,3,1,2,20,20,{margin},1"
        ),
        (
            f"Style: Hook,{hook_font},{hook_size},&H0000FFFF,&H000000FF,"
            f"&H00000000,&H80000000,1,0,0,0,100,100,0,0,1,4,2,8,40,40,80,1"
        ),
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]
    hook = " ".join(str(hook_text or "").split())
    if hook:
        safe_hook = _ass_text(hook)
        if len(safe_hook) > 48:
            safe_hook = safe_hook[:45] + "..."
        lines.append(
            f"Dialogue: 1,0:00:00.00,{_ts(max(0.6, hook_seconds))},Hook,,0,0,0,,{safe_hook}"
        )
    for seg in valid_segments(segments):
        start = max(0.0, float(seg["start"]))
        end = max(start + 0.2, float(seg["end"]))
        text = " ".join(str(seg.get("text", "")).split())
        if not text:
            continue
        chunks = textwrap.wrap(text, width=width) or [text]
        span = (end - start) / len(chunks)
        for i, chunk in enumerate(chunks):
            safe = _ass_text(chunk)
            lines.append(
                f"Dialogue: 0,{_ts(start + i * span)},{_ts(start + (i + 1) * span)},"
                f"Cap,,0,0,0,,{safe}"
            )
    return "\n".join(lines) + "\n"


def write_ass(
    segments: list[dict],
    path: Path,
    style: str = "default",
    resolution: tuple[int, int] = (1080, 1920),
    hook_text: str = "",
    hook_seconds: float = 2.0,
) -> Path:
    path.write_text(
        segments_to_ass(
            segments,
            style=style,
            play_res_x=resolution[0],
            play_res_y=resolution[1],
            hook_text=hook_text,
            hook_seconds=hook_seconds,
        ),
        encoding="utf-8",
    )
    return path


def burn_filter(ass_path: Path) -> str:
    escaped = str(ass_path).replace("\\", "/").replace(":", "\\:").replace("'", "\\'")
    return f"subtitles='{escaped}'"
