"""Automatic captions: Whisper timestamps -> styled ASS subtitle track."""
from __future__ import annotations

import textwrap
from pathlib import Path

STYLES = {
    "default": {"fontname": "Arial", "fontsize": 18, "primary": "&H00FFFFFF",
                "outline": "&H00000000", "bold": 1, "marginv": 40},
    "karaoke": {"fontname": "Arial", "fontsize": 22, "primary": "&H0000FFFF",
                "outline": "&H00000000", "bold": 1, "marginv": 60},
    "clean": {"fontname": "Helvetica", "fontsize": 16, "primary": "&H00F8F8F8",
              "outline": "&H50000000", "bold": 0, "marginv": 30},
}


def _ts(t: float) -> str:
    h = int(t // 3600)
    m = int((t % 3600) // 60)
    s = t % 60
    return f"{h}:{m:02d}:{s:05.2f}"


def segments_to_ass(segments: list[dict], style: str = "default",
                    play_res_x: int = 1080, play_res_y: int = 1920,
                    max_chars: int = 42) -> str:
    st = STYLES.get(style, STYLES["default"])
    lines = [
        "[Script Info]",
        "; generated by ClipForge worker",
        f"PlayResX: {play_res_x}",
        f"PlayResY: {play_res_y}",
        "ScaledBorderAndShadow: yes",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
        "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
        "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        (f"Style: Cap,{st['fontname']},{st['fontsize']},{st['primary']},&H000000FF,"
         f"{st['outline']},&H80000000,{st['bold']},0,0,0,100,100,0,0,1,2,1,2,20,20,{st['marginv']},1"),
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]
    for seg in segments:
        start = max(0.0, float(seg["start"]))
        end = max(start + 0.2, float(seg["end"]))
        text = " ".join(str(seg.get("text", "")).split())
        if not text:
            continue
        chunks = textwrap.wrap(text, width=max_chars) or [text]
        span = (end - start) / len(chunks)
        for i, chunk in enumerate(chunks):
            safe = chunk.replace("{", "(").replace("}", ")")
            lines.append(
                f"Dialogue: 0,{_ts(start + i * span)},{_ts(start + (i + 1) * span)},"
                f"Cap,,0,0,0,,{safe}"
            )
    return "\n".join(lines) + "\n"


def write_ass(segments: list[dict], path: Path, style: str = "default",
              resolution: tuple[int, int] = (1080, 1920)) -> Path:
    path.write_text(
        segments_to_ass(segments, style=style, play_res_x=resolution[0], play_res_y=resolution[1]),
        encoding="utf-8",
    )
    return path


def burn_filter(ass_path: Path) -> str:
    """ffmpeg -vf fragment that burns the caption file into the video."""
    escaped = str(ass_path).replace("\\", "/").replace(":", "\\:").replace("'", "\\'")
    return f"subtitles='{escaped}'"
