"""Automatic captions: Whisper timestamps -> styled ASS subtitle track."""
from __future__ import annotations

import textwrap
from pathlib import Path

STYLES = {
    "default": {
        "fontname": "Arial", "fontsize": 18, "primary": "&H00FFFFFF",
        "outline": "&H00000000", "bold": 1, "marginv": 40, "max_chars": 42,
    },
    "karaoke": {
        "fontname": "Arial", "fontsize": 22, "primary": "&H0000FFFF",
        "outline": "&H00000000", "bold": 1, "marginv": 60, "max_chars": 36,
    },
    "clean": {
        "fontname": "Helvetica", "fontsize": 16, "primary": "&H00F8F8F8",
        "outline": "&H50000000", "bold": 0, "marginv": 30, "max_chars": 44,
    },
    "bold": {
        "fontname": "Arial Black", "fontsize": 24, "primary": "&H00FFFFFF",
        "outline": "&H00000000", "bold": 1, "marginv": 50, "max_chars": 32,
    },
    "bengali": {
        "fontname": "Noto Sans Bengali", "fontsize": 26, "primary": "&H00FFFFFF",
        "outline": "&H00000000", "bold": 1, "marginv": 70, "max_chars": 28,
    },
    "hindi": {
        "fontname": "Noto Sans Devanagari", "fontsize": 26, "primary": "&H00FFFFFF",
        "outline": "&H00000000", "bold": 1, "marginv": 70, "max_chars": 28,
    },
}

CAPTION_STYLES = tuple(STYLES.keys())


def _ts(t: float) -> str:
    h = int(t // 3600)
    m = int((t % 3600) // 60)
    s = t % 60
    return f"{h}:{m:02d}:{s:05.2f}"


def segments_to_ass(
    segments: list[dict],
    style: str = "default",
    play_res_x: int = 1080,
    play_res_y: int = 1920,
    max_chars: int | None = None,
    hook_text: str = "",
    hook_seconds: float = 2.0,
) -> str:
    st = STYLES.get(style, STYLES["default"])
    width = max_chars if max_chars is not None else int(st.get("max_chars", 42))
    hook_font = "Arial Black" if style not in ("bengali", "hindi") else st["fontname"]
    lines = [
        "[Script Info]",
        "; generated by ClipForge worker",
        f"PlayResX: {play_res_x}",
        f"PlayResY: {play_res_y}",
        "ScaledBorderAndShadow: yes",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
        "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
        "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        (
            f"Style: Cap,{st['fontname']},{st['fontsize']},{st['primary']},&H000000FF,"
            f"{st['outline']},&H80000000,{st['bold']},0,0,0,100,100,0,0,1,3,1,2,20,20,{st['marginv']},1"
        ),
        (
            f"Style: Hook,{hook_font},42,&H0000FFFF,&H000000FF,"
            f"&H00000000,&H80000000,1,0,0,0,100,100,0,0,1,4,2,8,40,40,80,1"
        ),
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]
    hook = " ".join(str(hook_text or "").split())
    if hook:
        safe_hook = hook.replace("{", "(").replace("}", ")")
        if len(safe_hook) > 48:
            safe_hook = safe_hook[:45] + "..."
        lines.append(
            f"Dialogue: 1,0:00:00.00,{_ts(max(0.6, hook_seconds))},Hook,,0,0,0,,{safe_hook}"
        )
    for seg in segments:
        start = max(0.0, float(seg["start"]))
        end = max(start + 0.2, float(seg["end"]))
        text = " ".join(str(seg.get("text", "")).split())
        if not text:
            continue
        chunks = textwrap.wrap(text, width=width) or [text]
        span = (end - start) / len(chunks)
        for i, chunk in enumerate(chunks):
            safe = chunk.replace("{", "(").replace("}", ")")
            lines.append(
                f"Dialogue: 0,{_ts(start + i * span)},{_ts(start + (i + 1) * span)},"
                f"Cap,,0,0,0,,{safe}"
            )
    return "\n".join(lines) + "\n"


def write_ass(
    segments: list[dict],
    path: Path,
    style: str = "default",
    resolution: tuple[int, int] = (1080, 1920),
    hook_text: str = "",
    hook_seconds: float = 2.0,
) -> Path:
    path.write_text(
        segments_to_ass(
            segments,
            style=style,
            play_res_x=resolution[0],
            play_res_y=resolution[1],
            hook_text=hook_text,
            hook_seconds=hook_seconds,
        ),
        encoding="utf-8",
    )
    return path


def burn_filter(ass_path: Path) -> str:
    escaped = str(ass_path).replace("\\", "/").replace(":", "\\:").replace("'", "\\'")
    return f"subtitles='{escaped}'"
